name: build_pipeline

trigger:
  branches:
    include:
      - master

variables:
  BuildID: $[variables['Build.BuildId']]
  DOCKER_USERNAME: $[variables['DOCKERHUB_USERNAME']]
  CONTAINER_NAME: $[variables['CONTAINER_NAME']]

pool:
  Default

jobs:
  - deployment: build_push_container
    environment: 'main.server'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: checkout golang repo

          - script: |
              echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
            displayName: login docker

          - task: Docker@2
            displayName: build and push
            inputs:
              repository: "$(DOCKER_USERNAME)/$(CONTAINER_NAME)"
              command: 'buildAndPush'
              Dockerfile: './Dockerfile'
              buildContext: './'
              tags: '$(BuildID)'
