resources:
  pipelines:
    - pipeline: building_pipeline
      source: build_pipeline
      trigger: true

pool:
  Default

jobs:
  - job: debug
    steps:
      - script: |
          echo "Hello World!"