trigger: none

resources:
  pipelines:
    - pipeline: building
      source: Hakob771.golang-webserver
      trigger: true

pool:
  Default

jobs:
  - job: debug
    steps:
      - script: |
          echo "Hello World!"