trigger:
  branches:
    include:
      - master

pool:
  Default

jobs:
  - deployment: build_go_app
    environment: 'golang.go'
    strategy:
     runOnce:
       deploy:
         steps:
           - checkout: self
             displayName: checkout repo

           - script: |
               hostname
               go mod init webserver.go
               go mod tidy
               go build
             displayName: build app

  - deployment: publish
    environment: 'golang.go'
    dependsOn: build_go_app
    strategy:
     runOnce:
       deploy:
         steps:
          - script: |
              echo "##vso[task.setvariable variable=path]`pwd`"
          - task: UniversalPackages@0
            inputs:
              command: 'publish'
              publishDirectory: '$(Build.ArtifactStagingDirectory)'
              feedsToUsePublish: 'internal'
              vstsFeedPublish: '90d10e4b-4092-4999-9324-1654858e1908'
              publishPackageMetadata: false
              vstsFeedPackagePublish: 'Esim'
              versionOption: 'minor'