trigger:
  branches:
    include:
      - master

variables:
  BuildID: $[variables['Build.BuildId']]
  DOCKER_USERNAME: hakobmkoyan771

pool:
  Default

jobs:
  - job: build_push_container
    steps:
      - script: |
          echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
        displayName: login docker

      - task: Docker@2
        displayName: build and push
        inputs:
          repository: 'hakobmkoyan771'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          buildContext: './'
          tags: '$(BuildID)'