trigger: none

resources:
  pipelines:
    - pipeline: building
      source: Hakob771.golang-webserver
      trigger: true

pool:
  Default

variables:
  - group: container

jobs:
  - deployment: 'deploy_application'
    environment: 'main.server'
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                docker run -d -p 8097:80 $(DOCKERHUB_USERNAME)/$(CONTAINER_NAME):$(resources.pipeline.building.pipelineID)
              displayName: deploy container