trigger:
  branches:
    include:
      - master

pool:
  Default

jobs:
  - deployment: build_go_app
    environment: 'golang.go'
    strategy:
     runOnce:
       deploy:
         steps:
           - checkout: self
             displayName: checkout repo

           - script: |
               hostname
               go mod init webserver.go
               go mod tidy
               go build
             displayName: build app

  - deployment: publish
    environment: 'golang.go'
    dependsOn: build_go_app
    strategy:
     runOnce:
       deploy:
         steps:
           - script: |
               echo "##vso[task.setvariable variable=path]`pwd`"
           - publish: $(path)
             artifact: 'WebApp'
             displayName: publish app