trigger:
  branches:
    include:
      - master

variables:
  BuildID: $[variables['Build.BuildId']]
  DOCKER_USERNAME: hakobmkoyan771

pool:
  Default

jobs:
  - deployment: build_push_container
    environment: 'Work.worker-node'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
            displayName: login docker

          - script: | 
              ls
            displayName: debug

          - task: Docker@2
            displayName: build and push
            inputs:
              repository: 'hakobmkoyan771/demo_app'
              command: 'buildAndPush'
              Dockerfile: './Dockerfile'
              buildContext: './'
              tags: '$(BuildID)'
