trigger:
  branches:
    include:
      - master

pool:
  Default

jobs:
  - deployment: build_go_app
    environment: 'golang'
    strategy:
     runOnce:
       deploy:
         steps:
           - script: |
               hostname
               go mod tidy
               go build

  - deployment: publish
    environment: 'golang'
    strategy:
     runOnce:
       deploy:
         steps:
           - publish: ./*
             artifact: 'WebApp'