trigger:
  branches:
    include:
      - master

variables:
  BuildID: variables['Build.BuildId']

pool:
  Default

jobs:
  - job: build_push_container
    steps:
      - script: |
          docker version
        displayName: If docker is installed

      - task: DockerInstaller@0
        condition: failed()
        inputs:
          dockerVersion: '20.10.21'
          releaseType: stable

      - task: Docker@2
        displayName: build and push
        inputs:
          repository: 'hakobmkoyan771'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          buildContext: './'
          tags: '$(BuildID)'
          containerRegistry: "https://index.docker.io/v1/"