resources:
  pipelines:
    - pipeline: building_pipeline
      source: azure-pipelines
      project: https://dev.azure.com/hakobmkoyan771
      trigger: true

pool:
  Default

jobs:
  - job: debug
    steps:
      - script: |
          echo "Hello World!"