resources:
  pipelines:
    - pipeline: "building_pipeline"
      source: "build_pipeline"
      project: "digital"
      trigger: 
        branches:
          include:
            - master/azure-pipelines-1.yml

pool:
  Default

jobs:
  - job: debug
    steps:
      - script: |
          echo "Hello World!"