pr:
  branches:
    include:
      - master

jobs:
  - job: launch_vm
    pool:
      Default
    steps:
    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      displayName: Install Azure CLI

    - task: AzureCLI@2
      displayName: Create Resource Group
      inputs:
        azureSubscription: 'Azure subscription 1(e7d806da-b59d-43d3-97cc-ce664a6d9e1b)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group create --name myResourceGroup --location eastus'